// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const transferV400 = table("transfer_v4_0_0", {
  from: db.address('from'),
  to: db.address('to'),
  value: db.uint256('value'),
  txHash: db.bytes32('tx_hash'),
  tokenContext: t.text('token_context'),
})
